---
title: "Using DImodelsVis with regression models fit using the `DImodelsMulti` R package"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Using DImodelsVis with regression models fit using the `DImodelsMulti` R package}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE, comment = "#>",
  echo = TRUE, warning = FALSE, message = FALSE,
  fig.width = 8, fig.height = 5, fig.align = "center",
  class.source = "fold-show", eval = TRUE
)
```

### Loading necessary libraries

```{r setup}
library(DImodels)
library(DImodelsVis)
library(DImodelsMulti)
library(dplyr)
library(ggplot2)
```

### Data exploration

#### Load data

```{r, load-data}
head(dataBEL)
```

#### Visualisations for data exploration

```{r}

```


### Model fitting

```{r, models}
# Name of compositional predictors (species)
species <- c("G1", "G2", "L1", "L2")
# Functional groupings of species
FG <- c("Gr", "Gr", "Le", "Le")
# Colours to be used for pie-glyphs for all figures
pie_cols <- get_colours(vars = species, FG = FG)

model <- DImulti(prop = species, FG = FG, y = "Y", 
                 eco_func = c("Var", "un"),
                 unit_IDs = "Plot", DImodel = "AV",
                 extra_fixed = ~ Density,
                 method = "REML", data = dataBEL)
model
```


```{r, model-diagnostics1, fig.height=5, fig.width=8}
model_diagnostics(model = model, which = c(1, 2), nrow = 1)
```

```{r, model-diagnostics2, fig.height=9, fig.width=12}
model_diagnostics(model = model, which = c(1, 2), nrow = 2) + 
  facet_wrap(~Var)
```

```{r, gradient-change, fig.width=12, fig.height=5}
grad_data <- get_equi_comms(4, variables = c("G1", "G2", "L1", "L2")) %>%
  mutate("Rich." = Richness,
         "Density" = factor(1, levels = c(-1, 1)))

gradient_change(model = model, data = grad_data, nrow = 1)
```


```{r, cond-tern, fig.height=8, fig.width=9}
conditional_ternary(model = model, resolution = 1,
                    tern_vars = c("G1", "G2", "L2"),
                    conditional = data.frame(L1 = c(0, 0.25, 0.5)),
                    lower_lim = 30, upper_lim = 110, nlevels = 8,
                    add_var = list("Density" = factor(1, levels = c(-1, 1))), 
                    nrow = 3)
```


```{r, grouped-tern, fig.height=9, fig.width=4}
grouped_ternary(model = model, resolution = 1,
                FG = c("G", "G", "L1", "L2"),
                # Split of species within each group
                values = c(0.5, 0.5, 1, 1),
                lower_lim = 30, upper_lim = 110, nlevels = 8,
                add_var = list("Density" = factor(1, levels = c(-1, 1))), 
                nrow = 3)
```

```{r, effects-plot, fig.height = 12, fig.width = 6}
eff_data <- get_equi_comms(4, variables = c("G1", "G2", "L1", "L2")) %>%
  mutate("Rich." = Richness)

visualise_effects(model = model, data = eff_data, 
                  add_var = list("Density" = factor(-1, levels = c(-1, 1))),
                  var_interest = c("L1", "L2"), nrow = 3)
```


```{r, simplex-path, fig.width=12, fig.height=5}
# The centroid community (starting point for the straight line)
starts <- tribble( ~G1,  ~G2,  ~L1,  ~L2,
                  0.25, 0.25, 0.25, 0.25)
# The six binary mixtures (ending points for the straight lines)
ends <- tribble(~G1,    ~G2,  ~L1,  ~L2,
                  0.5,  0.5,    0,    0,
                  0.5,    0,  0.5,    0,
                  0.5,    0,    0,  0.5,
                    0,  0.5,  0.5,    0,
                    0,  0.5,    0,  0.5,
                    0,    0,  0.5,  0.5)

# Create the visualisation
simplex_path(model = model, 
             add_var = list("Density" = factor(-1, levels = c(-1, 1))),
             starts = starts, ends = ends,
             nrow = 1)
```


```{r, pred-cont, fig.width=8, fig.height=14}
pred_data <- get_equi_comms(4, richness_lvl = c(1, 2, 4),
                            variables = c("G1", "G2", "L1", "L2")) %>%
  mutate(labels = c("G1_mono", "G1_mono", "G1_mono", "L2_mono",
                    "G1-G2", "G1-L1", "G1-L2", "G2-L1", "G2-L2", "L1-L2",
                    "Centroid")) %>% 
  add_add_var(add_var = list("Var" = c("N", "Sown", "Weed"))) %>% 
  mutate(G1_ID = G1, G2_ID = G2, L1_ID = L1, L2_ID = L2,
         "Density" = factor(-1, levels = c(-1, 1)),
         AV = DI_data_E_AV(prop = 1:4, data = .)$AV,
         "Rich." = Richness)

prediction_contributions_data(data = pred_data, model = model, 
                              bar_labs = "labels",
                              groups = list("G1" = 1:3, "G2" = 4:6,
                                            "L1" = 7:9, "L2" = 10:12,
                                            "AV" = 13:15, "Density" = 16:18)) %>% 
  prediction_contributions_plot(colours = c(pie_cols, "#303030", "steelblue3"),
                                nrow = 3) +
  facet_grid(~ Rich., scale = "free_x", space = "free_x") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1.1, vjust = 1.1))
```
